/**
 * Icons offered for files and folders in the tree: Phosphor, drawn duotone.
 * Names are kebab-case Phosphor names ("book-open"); they are what ~/.onyx stores.
 * App chrome (chevrons, toolbar buttons) uses Lucide through iconCatalog.ts instead.
 */
import type { Icon as PhosphorIcon } from "@phosphor-icons/react";
import {
  AirplaneIcon, AirplaneTiltIcon, AlarmIcon, AlienIcon, AnchorIcon, AppleLogoIcon, ArchiveIcon,
  ArticleIcon, AsteriskIcon, AtIcon, AtomIcon, BabyIcon, BackpackIcon, BalloonIcon, BankIcon,
  BarbellIcon, BathtubIcon, BedIcon, BeerSteinIcon, BellIcon, BicycleIcon, BirdIcon, BoatIcon,
  BookIcon, BookBookmarkIcon, BookOpenIcon, BookOpenTextIcon, BookmarkIcon, BookmarkSimpleIcon,
  BookmarksIcon, BooksIcon, BracketsCurlyIcon, BrainIcon, BriefcaseIcon, BugIcon, BuildingIcon,
  BuildingsIcon, ButterflyIcon, CactusIcon, CakeIcon, CalendarIcon, CalendarBlankIcon,
  CalendarCheckIcon, CalendarDotsIcon, CameraIcon, CarIcon, CarrotIcon, CatIcon,
  ChalkboardIcon, ChalkboardTeacherIcon, ChartBarIcon, ChartLineIcon, ChartPieIcon,
  ChatCircleIcon, ChatsCircleIcon, CheckCircleIcon, CheckSquareIcon, ChecksIcon, ChurchIcon,
  CircleIcon, ClipboardIcon, ClipboardTextIcon, ClockIcon, CloudIcon, CloudArrowUpIcon,
  CloudRainIcon, CodeIcon, CodeBlockIcon, CoffeeIcon, CoffeeBeanIcon, CompassIcon,
  ConfettiIcon, CookingPotIcon, CouchIcon, CpuIcon, CrownIcon, CubeIcon, CurrencyDollarIcon,
  DatabaseIcon, DesktopIcon, DetectiveIcon, DeviceMobileIcon, DiamondIcon, DogIcon, DressIcon,
  DropIcon, EnvelopeIcon, EnvelopeOpenIcon, EraserIcon, ExamIcon, EyeIcon, EyeSlashIcon,
  FeatherIcon, FileIcon, FileAudioIcon, FileCodeIcon, FileCsvIcon, FileDocIcon, FileImageIcon,
  FileMdIcon, FilePdfIcon, FileTextIcon, FileVideoIcon, FileZipIcon, FilesIcon, FilmSlateIcon,
  FilmStripIcon, FireIcon, FirstAidIcon, FishIcon, FlagIcon, FlagBannerIcon, FlaskIcon,
  FlowerIcon, FlowerLotusIcon, FlowerTulipIcon, FolderIcon, FolderDashedIcon, FolderLockIcon,
  FolderOpenIcon, FolderPlusIcon, FolderSimpleIcon, FolderSimpleStarIcon, FolderStarIcon,
  FolderUserIcon, FoldersIcon, ForkKnifeIcon, FunctionIcon, GameControllerIcon, GavelIcon,
  GearIcon, GhostIcon, GiftIcon, GitBranchIcon, GitCommitIcon, GitPullRequestIcon,
  GithubLogoIcon, GlobeIcon, GlobeHemisphereWestIcon, GraduationCapIcon, GraphIcon, GuitarIcon,
  HamburgerIcon, HandHeartIcon, HandWavingIcon, HandshakeIcon, HardDrivesIcon, HashIcon,
  HeadphonesIcon, HeartIcon, HeartHalfIcon, HeartbeatIcon, HexagonIcon, HorseIcon,
  HospitalIcon, HourglassIcon, HouseIcon, HouseLineIcon, ImageIcon, ImagesIcon, InfinityIcon,
  InfoIcon, IslandIcon, KanbanIcon, KeyIcon, KeyboardIcon, LampIcon, LaptopIcon, LeafIcon,
  LightbulbIcon, LighthouseIcon, LightningIcon, ListBulletsIcon, ListChecksIcon, LockIcon,
  LockOpenIcon, MagnifyingGlassIcon, MapPinIcon, MapPinLineIcon, MapTrifoldIcon, MaskHappyIcon,
  MedalIcon, MegaphoneIcon, MicrophoneIcon, MinusIcon, MoneyIcon, MoonIcon, MoonStarsIcon,
  MountainsIcon, MusicNoteIcon, MusicNotesIcon, NewspaperIcon, NoteIcon, NotePencilIcon,
  NotebookIcon, NotepadIcon, OctagonIcon, PackageIcon, PaintBrushIcon, PaintBucketIcon,
  PaletteIcon, PaperclipIcon, ParkIcon, PawPrintIcon, PeaceIcon, PenNibIcon, PencilIcon,
  PencilSimpleIcon, PersonSimpleIcon, PersonSimpleRunIcon, PersonSimpleTaiChiIcon,
  PersonSimpleWalkIcon, PhoneIcon, PianoKeysIcon, PillIcon, PizzaIcon, PlantIcon, PlugsIcon,
  PlusIcon, PresentationIcon, PresentationChartIcon, ProhibitIcon, PushPinIcon, QuestionIcon,
  QuotesIcon, RabbitIcon, RainbowIcon, ReceiptIcon, RecycleIcon, RobotIcon, RocketIcon,
  ScalesIcon, ScissorsIcon, ScrollIcon, SealIcon, SealCheckIcon, ShieldIcon, ShieldCheckIcon,
  ShoppingBagIcon, ShoppingCartIcon, SignpostIcon, SkullIcon, SmileyIcon, SmileySadIcon,
  SnowflakeIcon, SparkleIcon, SquareIcon, StackIcon, StarIcon, StethoscopeIcon, StorefrontIcon,
  StudentIcon, SuitcaseIcon, SuitcaseRollingIcon, SunIcon, TShirtIcon, TagIcon, TargetIcon,
  TelevisionIcon, TentIcon, TerminalIcon, TerminalWindowIcon, TestTubeIcon, TextAaIcon,
  TicketIcon, TimerIcon, ToolboxIcon, ToteIcon, TrainIcon, TranslateIcon, TrashIcon, TrayIcon,
  TreeIcon, TreeEvergreenIcon, TreeStructureIcon, TreeViewIcon, TriangleIcon, TrophyIcon,
  UserIcon, UserCircleIcon, UsersIcon, UsersThreeIcon, VideoCameraIcon, WalletIcon,
  WarningIcon, WarningCircleIcon, WavesIcon, WindIcon, WineIcon, WrenchIcon, XIcon,
  YinYangIcon,
} from "@phosphor-icons/react";

export const TREE_ICON_MAP: Record<string, PhosphorIcon> = {
  "folder": FolderIcon,
  "folder-open": FolderOpenIcon,
  "folder-simple": FolderSimpleIcon,
  "folder-simple-star": FolderSimpleStarIcon,
  "folder-star": FolderStarIcon,
  "folder-lock": FolderLockIcon,
  "folder-user": FolderUserIcon,
  "folder-plus": FolderPlusIcon,
  "folder-dashed": FolderDashedIcon,
  "folders": FoldersIcon,
  "archive": ArchiveIcon,
  "tray": TrayIcon,
  "file": FileIcon,
  "file-text": FileTextIcon,
  "file-md": FileMdIcon,
  "file-code": FileCodeIcon,
  "file-image": FileImageIcon,
  "file-pdf": FilePdfIcon,
  "file-audio": FileAudioIcon,
  "file-video": FileVideoIcon,
  "file-zip": FileZipIcon,
  "file-csv": FileCsvIcon,
  "file-doc": FileDocIcon,
  "files": FilesIcon,
  "note": NoteIcon,
  "note-pencil": NotePencilIcon,
  "notepad": NotepadIcon,
  "paperclip": PaperclipIcon,
  "clipboard": ClipboardIcon,
  "clipboard-text": ClipboardTextIcon,
  "scroll": ScrollIcon,
  "stack": StackIcon,
  "book": BookIcon,
  "book-open": BookOpenIcon,
  "book-open-text": BookOpenTextIcon,
  "book-bookmark": BookBookmarkIcon,
  "books": BooksIcon,
  "bookmark": BookmarkIcon,
  "bookmark-simple": BookmarkSimpleIcon,
  "bookmarks": BookmarksIcon,
  "notebook": NotebookIcon,
  "newspaper": NewspaperIcon,
  "article": ArticleIcon,
  "brain": BrainIcon,
  "lightbulb": LightbulbIcon,
  "student": StudentIcon,
  "graduation-cap": GraduationCapIcon,
  "chalkboard": ChalkboardIcon,
  "exam": ExamIcon,
  "quotes": QuotesIcon,
  "text-aa": TextAaIcon,
  "translate": TranslateIcon,
  "globe": GlobeIcon,
  "globe-hemisphere-west": GlobeHemisphereWestIcon,
  "magnifying-glass": MagnifyingGlassIcon,
  "detective": DetectiveIcon,
  "graph": GraphIcon,
  "tree-structure": TreeStructureIcon,
  "tree-view": TreeViewIcon,
  "map-trifold": MapTrifoldIcon,
  "compass": CompassIcon,
  "briefcase": BriefcaseIcon,
  "calendar": CalendarIcon,
  "calendar-blank": CalendarBlankIcon,
  "calendar-check": CalendarCheckIcon,
  "calendar-dots": CalendarDotsIcon,
  "clock": ClockIcon,
  "hourglass": HourglassIcon,
  "timer": TimerIcon,
  "alarm": AlarmIcon,
  "check-square": CheckSquareIcon,
  "check-circle": CheckCircleIcon,
  "list-checks": ListChecksIcon,
  "list-bullets": ListBulletsIcon,
  "kanban": KanbanIcon,
  "target": TargetIcon,
  "flag": FlagIcon,
  "flag-banner": FlagBannerIcon,
  "trophy": TrophyIcon,
  "medal": MedalIcon,
  "rocket": RocketIcon,
  "chart-line": ChartLineIcon,
  "chart-bar": ChartBarIcon,
  "chart-pie": ChartPieIcon,
  "presentation-chart": PresentationChartIcon,
  "presentation": PresentationIcon,
  "handshake": HandshakeIcon,
  "money": MoneyIcon,
  "wallet": WalletIcon,
  "currency-dollar": CurrencyDollarIcon,
  "receipt": ReceiptIcon,
  "bank": BankIcon,
  "scales": ScalesIcon,
  "gavel": GavelIcon,
  "buildings": BuildingsIcon,
  "storefront": StorefrontIcon,
  "code": CodeIcon,
  "code-block": CodeBlockIcon,
  "terminal": TerminalIcon,
  "terminal-window": TerminalWindowIcon,
  "bug": BugIcon,
  "git-branch": GitBranchIcon,
  "git-commit": GitCommitIcon,
  "git-pull-request": GitPullRequestIcon,
  "github-logo": GithubLogoIcon,
  "database": DatabaseIcon,
  "hard-drives": HardDrivesIcon,
  "cloud": CloudIcon,
  "cloud-arrow-up": CloudArrowUpIcon,
  "cpu": CpuIcon,
  "robot": RobotIcon,
  "desktop": DesktopIcon,
  "laptop": LaptopIcon,
  "device-mobile": DeviceMobileIcon,
  "keyboard": KeyboardIcon,
  "gear": GearIcon,
  "wrench": WrenchIcon,
  "toolbox": ToolboxIcon,
  "plugs": PlugsIcon,
  "cube": CubeIcon,
  "package": PackageIcon,
  "atom": AtomIcon,
  "flask": FlaskIcon,
  "test-tube": TestTubeIcon,
  "function": FunctionIcon,
  "brackets-curly": BracketsCurlyIcon,
  "user": UserIcon,
  "users": UsersIcon,
  "users-three": UsersThreeIcon,
  "user-circle": UserCircleIcon,
  "baby": BabyIcon,
  "person-simple": PersonSimpleIcon,
  "person-simple-walk": PersonSimpleWalkIcon,
  "person-simple-run": PersonSimpleRunIcon,
  "heart": HeartIcon,
  "heart-half": HeartHalfIcon,
  "smiley": SmileyIcon,
  "smiley-sad": SmileySadIcon,
  "hand-heart": HandHeartIcon,
  "hand-waving": HandWavingIcon,
  "chat-circle": ChatCircleIcon,
  "chats-circle": ChatsCircleIcon,
  "envelope": EnvelopeIcon,
  "envelope-open": EnvelopeOpenIcon,
  "phone": PhoneIcon,
  "megaphone": MegaphoneIcon,
  "gift": GiftIcon,
  "cake": CakeIcon,
  "confetti": ConfettiIcon,
  "balloon": BalloonIcon,
  "house": HouseIcon,
  "house-line": HouseLineIcon,
  "building": BuildingIcon,
  "church": ChurchIcon,
  "hospital": HospitalIcon,
  "chalkboard-teacher": ChalkboardTeacherIcon,
  "tent": TentIcon,
  "airplane": AirplaneIcon,
  "airplane-tilt": AirplaneTiltIcon,
  "car": CarIcon,
  "bicycle": BicycleIcon,
  "train": TrainIcon,
  "boat": BoatIcon,
  "anchor": AnchorIcon,
  "map-pin": MapPinIcon,
  "map-pin-line": MapPinLineIcon,
  "signpost": SignpostIcon,
  "suitcase": SuitcaseIcon,
  "suitcase-rolling": SuitcaseRollingIcon,
  "backpack": BackpackIcon,
  "mountains": MountainsIcon,
  "island": IslandIcon,
  "park": ParkIcon,
  "lighthouse": LighthouseIcon,
  "sun": SunIcon,
  "moon": MoonIcon,
  "moon-stars": MoonStarsIcon,
  "star": StarIcon,
  "sparkle": SparkleIcon,
  "cloud-rain": CloudRainIcon,
  "snowflake": SnowflakeIcon,
  "lightning": LightningIcon,
  "fire": FireIcon,
  "drop": DropIcon,
  "wind": WindIcon,
  "rainbow": RainbowIcon,
  "leaf": LeafIcon,
  "plant": PlantIcon,
  "flower": FlowerIcon,
  "flower-lotus": FlowerLotusIcon,
  "flower-tulip": FlowerTulipIcon,
  "tree": TreeIcon,
  "tree-evergreen": TreeEvergreenIcon,
  "cactus": CactusIcon,
  "feather": FeatherIcon,
  "butterfly": ButterflyIcon,
  "bird": BirdIcon,
  "cat": CatIcon,
  "dog": DogIcon,
  "paw-print": PawPrintIcon,
  "fish": FishIcon,
  "horse": HorseIcon,
  "rabbit": RabbitIcon,
  "waves": WavesIcon,
  "image": ImageIcon,
  "images": ImagesIcon,
  "camera": CameraIcon,
  "film-strip": FilmStripIcon,
  "film-slate": FilmSlateIcon,
  "video-camera": VideoCameraIcon,
  "music-note": MusicNoteIcon,
  "music-notes": MusicNotesIcon,
  "headphones": HeadphonesIcon,
  "microphone": MicrophoneIcon,
  "guitar": GuitarIcon,
  "piano-keys": PianoKeysIcon,
  "palette": PaletteIcon,
  "paint-brush": PaintBrushIcon,
  "paint-bucket": PaintBucketIcon,
  "pencil": PencilIcon,
  "pencil-simple": PencilSimpleIcon,
  "pen-nib": PenNibIcon,
  "eraser": EraserIcon,
  "scissors": ScissorsIcon,
  "television": TelevisionIcon,
  "game-controller": GameControllerIcon,
  "ticket": TicketIcon,
  "mask-happy": MaskHappyIcon,
  "heartbeat": HeartbeatIcon,
  "pill": PillIcon,
  "first-aid": FirstAidIcon,
  "stethoscope": StethoscopeIcon,
  "barbell": BarbellIcon,
  "person-simple-tai-chi": PersonSimpleTaiChiIcon,
  "bed": BedIcon,
  "bathtub": BathtubIcon,
  "coffee": CoffeeIcon,
  "coffee-bean": CoffeeBeanIcon,
  "wine": WineIcon,
  "beer-stein": BeerSteinIcon,
  "fork-knife": ForkKnifeIcon,
  "cooking-pot": CookingPotIcon,
  "hamburger": HamburgerIcon,
  "pizza": PizzaIcon,
  "carrot": CarrotIcon,
  "apple-logo": AppleLogoIcon,
  "shopping-cart": ShoppingCartIcon,
  "shopping-bag": ShoppingBagIcon,
  "tote": ToteIcon,
  "t-shirt": TShirtIcon,
  "dress": DressIcon,
  "couch": CouchIcon,
  "lamp": LampIcon,
  "key": KeyIcon,
  "lock": LockIcon,
  "lock-open": LockOpenIcon,
  "shield": ShieldIcon,
  "shield-check": ShieldCheckIcon,
  "circle": CircleIcon,
  "square": SquareIcon,
  "triangle": TriangleIcon,
  "diamond": DiamondIcon,
  "hexagon": HexagonIcon,
  "octagon": OctagonIcon,
  "asterisk": AsteriskIcon,
  "hash": HashIcon,
  "at": AtIcon,
  "infinity": InfinityIcon,
  "crown": CrownIcon,
  "seal": SealIcon,
  "seal-check": SealCheckIcon,
  "question": QuestionIcon,
  "info": InfoIcon,
  "warning": WarningIcon,
  "warning-circle": WarningCircleIcon,
  "prohibit": ProhibitIcon,
  "checks": ChecksIcon,
  "x": XIcon,
  "plus": PlusIcon,
  "minus": MinusIcon,
  "tag": TagIcon,
  "push-pin": PushPinIcon,
  "eye": EyeIcon,
  "eye-slash": EyeSlashIcon,
  "bell": BellIcon,
  "recycle": RecycleIcon,
  "trash": TrashIcon,
  "yin-yang": YinYangIcon,
  "peace": PeaceIcon,
  "skull": SkullIcon,
  "ghost": GhostIcon,
  "alien": AlienIcon,
};

export const TREE_ICON_CATEGORIES: { name: string; icons: string[] }[] = [
  { name: "Folders & Files", icons: [
    "folder", "folder-open", "folder-simple", "folder-simple-star", "folder-star",
    "folder-lock", "folder-user", "folder-plus", "folder-dashed", "folders", "archive", "tray",
    "file", "file-text", "file-md", "file-code", "file-image", "file-pdf", "file-audio",
    "file-video", "file-zip", "file-csv", "file-doc", "files", "note", "note-pencil",
    "notepad", "paperclip", "clipboard", "clipboard-text", "scroll", "stack",
  ] },
  { name: "Knowledge", icons: [
    "book", "book-open", "book-open-text", "book-bookmark", "books", "bookmark",
    "bookmark-simple", "bookmarks", "notebook", "newspaper", "article", "brain", "lightbulb",
    "student", "graduation-cap", "chalkboard", "exam", "quotes", "text-aa", "translate",
    "globe", "globe-hemisphere-west", "magnifying-glass", "detective", "graph",
    "tree-structure", "tree-view", "map-trifold", "compass",
  ] },
  { name: "Work & Planning", icons: [
    "briefcase", "calendar", "calendar-blank", "calendar-check", "calendar-dots", "clock",
    "hourglass", "timer", "alarm", "check-square", "check-circle", "list-checks",
    "list-bullets", "kanban", "target", "flag", "flag-banner", "trophy", "medal", "rocket",
    "chart-line", "chart-bar", "chart-pie", "presentation-chart", "presentation", "handshake",
    "money", "wallet", "currency-dollar", "receipt", "bank", "scales", "gavel", "buildings",
    "storefront",
  ] },
  { name: "Code & Tech", icons: [
    "code", "code-block", "terminal", "terminal-window", "bug", "git-branch", "git-commit",
    "git-pull-request", "github-logo", "database", "hard-drives", "cloud", "cloud-arrow-up",
    "cpu", "robot", "desktop", "laptop", "device-mobile", "keyboard", "gear", "wrench",
    "toolbox", "plugs", "cube", "package", "atom", "flask", "test-tube", "function",
    "brackets-curly",
  ] },
  { name: "People", icons: [
    "user", "users", "users-three", "user-circle", "baby", "person-simple",
    "person-simple-walk", "person-simple-run", "heart", "heart-half", "smiley", "smiley-sad",
    "hand-heart", "hand-waving", "chat-circle", "chats-circle", "envelope", "envelope-open",
    "phone", "megaphone", "gift", "cake", "confetti", "balloon",
  ] },
  { name: "Places & Travel", icons: [
    "house", "house-line", "building", "church", "hospital", "chalkboard-teacher", "tent",
    "airplane", "airplane-tilt", "car", "bicycle", "train", "boat", "anchor", "map-pin",
    "map-pin-line", "signpost", "suitcase", "suitcase-rolling", "backpack", "mountains",
    "island", "park", "lighthouse",
  ] },
  { name: "Nature", icons: [
    "sun", "moon", "moon-stars", "star", "sparkle", "cloud-rain", "snowflake", "lightning",
    "fire", "drop", "wind", "rainbow", "leaf", "plant", "flower", "flower-lotus",
    "flower-tulip", "tree", "tree-evergreen", "cactus", "feather", "butterfly", "bird", "cat",
    "dog", "paw-print", "fish", "horse", "rabbit", "waves",
  ] },
  { name: "Media & Art", icons: [
    "image", "images", "camera", "film-strip", "film-slate", "video-camera", "music-note",
    "music-notes", "headphones", "microphone", "guitar", "piano-keys", "palette",
    "paint-brush", "paint-bucket", "pencil", "pencil-simple", "pen-nib", "eraser", "scissors",
    "television", "game-controller", "ticket", "mask-happy",
  ] },
  { name: "Health & Home", icons: [
    "heartbeat", "pill", "first-aid", "stethoscope", "barbell", "person-simple-tai-chi", "bed",
    "bathtub", "coffee", "coffee-bean", "wine", "beer-stein", "fork-knife", "cooking-pot",
    "hamburger", "pizza", "carrot", "apple-logo", "shopping-cart", "shopping-bag", "tote",
    "t-shirt", "dress", "couch", "lamp", "key", "lock", "lock-open", "shield", "shield-check",
  ] },
  { name: "Symbols", icons: [
    "circle", "square", "triangle", "diamond", "hexagon", "octagon", "asterisk", "hash", "at",
    "infinity", "crown", "seal", "seal-check", "question", "info", "warning", "warning-circle",
    "prohibit", "checks", "x", "plus", "minus", "tag", "push-pin", "eye", "eye-slash", "bell",
    "recycle", "trash", "yin-yang", "peace", "skull", "ghost", "alien",
  ] },
];

export const ALL_TREE_ICON_NAMES = TREE_ICON_CATEGORIES.flatMap((c) => c.icons);
